config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get 'followings' => 'relationships#following'
    get 'followed' => 'relationships#followed'
    resource :relationships, only: [:create, :destroy]
    get 'rooms' => 'rooms#chat_rooms'
  end
  post 'users/:id/book_count' => 'users#book_count', as: 'book_count'
  
  post 'search' => 'search#search', as: 'search'
  
  post 'dm/:id' => 'rooms#create_dm', as: 'start_dm'
  
  resources :rooms, only: [:index, :create, :show, :new, :edit, :update] do
    get 'detail' => 'rooms#detail', as: 'detail'
    get 'new_email' => 'rooms#new_email', as: 'new_email'
    post 'send_email' => 'rooms#send_email', as: 'send_email'
    resource :room_users, only: [:create, :destroy]
  end
  resources :chats, only: [:create, :index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image, destroy: false

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following_users, through: :follower, source: :followed
  
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followed_users, through: :followed, source: :follower
  
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  
  has_many :admin_rooms, class_name: 'Room', foreign_key: 'admin_id'
  
  has_many :chats
	
  def followed_by?(user)
    followed_users.where(id: user.id).exists?
  end
  
  def mutual_follow?(user)
    self.followed_by?(user) && user.followed_by?(self)
  end
  
  def self.search_contents(word, range)
  	if range == 0
  		self.where(['name LIKE?', "#{word}"])
  	elsif range == 1
  		self.where(['name LIKE?', "#{word}%"])
  	elsif range == 2
  		self.where(['name LIKE?', "%#{word}"])
  	elsif range == 3
  		self.where(['name LIKE?', "%#{word}%"])
  	end
  end
  
  def dm_room_for(user)
    my_dm_rooms_id = self.rooms.where(is_direct_message: true).pluck(:id)
    return user.rooms.find_by(id: [my_dm_rooms_id])
  end
  
  def count_books_for(date)
    self.books.where(created_at: date.all_day).count
  end
  
  def joined?(room)
    room_users.where(room_id: room.id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :book_count]
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @books = @user.books
    @book = Book.new
    @now = Time.current
    set_two_week
    @count_books = @books.where(created_at: @two_week)
    submit_count
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def book_count
    @counts = @user.count_books_for(params[:date].to_date)
    respond_to do |format|
      format.html {redirect_back(fallback_location: books_path)}
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def submit_count
    set_a_week
    set_last_week
    
    @today_counts, @yesterday_counts, @week_counts, @last_week_counts = 0, 0, 0, 0
    gon.daily_counts = [0, 0, 0, 0, 0, 0, 0]
    
    @count_books.each do |book|
      if @now.all_day.cover? book.created_at
        @today_counts += 1
        @week_counts += 1
        gon.daily_counts[6] += 1
      elsif @now.yesterday.all_day.cover? book.created_at
        @yesterday_counts += 1
        @week_counts += 1
        gon.daily_counts[5] += 1
      elsif @a_week.cover? book.created_at
        @week_counts += 1
        days_before = (@now.to_date - book.created_at.to_date).to_i
        gon.daily_counts[6 - days_before] += 1
      elsif @last_week.cover? book.created_at
        @last_week_counts += 1
      end
    end
  end
  
  def set_two_week
    from = @now.ago(13.days).at_beginning_of_day
    to = @now.at_end_of_day
    @two_week = from..to
  end
  
  def set_a_week
    from = @now.ago(6.days).at_beginning_of_day
    to = @now.at_end_of_day
    @a_week = from..to
    
    gon.days = []
    for i in 1..5 do
      i = 7 - i
      gon.days.push(@now.ago(i.days).strftime('%m/%d'))
      
    end
    gon.days.push('yesterday', 'today')
  end
  
  def set_last_week
    from = @now.ago(13.days).at_beginning_of_day
    to = @now.ago(7.days).at_end_of_day
    @last_week = from..to
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_chart.html.slim
canvas#bookLineChart

app/views/users/_index.html.slim
- if users.present?
  table.table
    thead
      tr
        th
          | image
        th
          | name
        th[colspan="6"]
    tbody
      - users.each do |user|
        tr
          td
            = attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg")
          td
            = user.name
          td
            | follow:
            = link_to user.follower.count, user_followings_path(user)
          td
            | followed by:
            = link_to user.followed.count, user_followed_path(user)
          td
            - unless page == 'search'
              - unless user == current_user
                = render 'relationships/follow_btn', user: user, page: page, display_user_id: display_user_id
          td
            = link_to 'Show', user, class: "user_#{user.id}"

- else
  p
    | No User

app/views/users/_info.html.slim
.user_info
  table.table
    tr
      = attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg")
    tr
      th
        | name
      th
        = user.name
    tr
      th
        | introduction
      th
        = user.introduction
    tr
      th
        | follow
      th
        = link_to user.follower.count, user_followings_path(user)
    tr
      th
        | followed by
      th
        = link_to user.followed.count, user_followed_path(user)
  |  　 
  .row
    - if user == current_user
      = link_to '', edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}"
    - else
      = render 'relationships/follow_btn', user: user, page: '', display_user_id: user.id
      = render 'rooms/dm_btn', user: user

app/views/users/_investigation.html.slim
= form_with url: book_count_path, html: {class: 'input-group'}, method: :post do |f|
  = f.hidden_field :id, value: user.id
  = f.date_field :date, class: 'form-control'
  = f.button :type => "submit", class: 'btn btn-info input-group-append' do
    i.fas.fa-history

.book_count_result
  table.table.table-bordered
    tr
      th.table-active
        | submit
      td#book_count_result

app/views/users/_statistics.html.slim
.statistics
  .book_count
    h3
      | Submit
    = render 'users/submit', today_counts: today_counts, yesterday_counts: yesterday_counts, week_counts: week_counts, last_week_counts: last_week_counts
      
  .chart
    h3
      | Daily Transition
    = render 'users/chart', now: now, daily_counts: daily_counts
    
  .search_book_count
    h3
      | Investigation
    .w-50
      = render 'users/investigation', user: user

app/views/users/_submit.html.slim
table.table.table-bordered
  tr
    th
      | Today
      
    th
      | Yesterday
    
    th
      | Comparison(%)
  tr
    td
      = today_counts
      
    td
      = yesterday_counts
      
    td
      - if yesterday_counts == 0
        = '--'
      - else
        = today_counts/yesterday_counts*100
        
table.table.table-bordered
  tr
    th
      | This week
      
    th
      | Last week
    th
      | Comparison(%)
  tr
    td
      = week_counts
      
    td
      = last_week_counts
    
    td
      - if last_week_counts == 0
        = '--'
      - else
        = week_counts/last_week_counts*100

app/views/users/book_count.js.erb
$('.book_count_result').css('display','block');
$('#book_count_result').html('<%= @counts %>');

app/views/users/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | User info
      = form_with model:@user, local:true do |f|
        = render 'layouts/errors', obj: @user
        .form-group
          = f.label :name
          = f.text_field :name, class: "form-control name"
        .form-group
          = f.label :image
          = f.attachment_field :profile_image, class: "form-control-file user_image"
        .form-group
          = f.label :introduction
          = f.text_area :introduction, class: "form-control introduction"
        .form-group
          = f.submit class: 'btn btn-secondary'

app/views/users/index.html.slim
= render 'search/form'
.container.px-5.px-sm-0
  .row
    .col-md-3
      h2
        | User info
      = render 'info', user: current_user
      h2.mt-3
        | New book
      = render 'books/form', book: @book
    .col-md-8.offset-md-1
      h2.d-inline-block
        | Users
      .links.d-inline-block.float-right
        = link_to "Create Room", new_room_path, class: "btn btn-success mr-2"
        = link_to "Rooms", rooms_path, class: "btn btn-outline-info"
      
      .users
        = render 'index',users: @users, page: 'index', display_user_id: current_user.id

app/views/users/show.html.slim
= render 'search/form'
.container.px-5.px-sm-0
  .row
    .col-md-3
      h2
        | User info
      = render 'info', user: @user
      h2.mt-3
        | New book
      = render 'books/form', book: @book
    .col-md-8.offset-md-1
      h2
        | Books
      = render 'books/index',books: @books
      
      h2
        | Statistics

      .statistics
        .book_count
          h3
            | Submit
          = render 'users/submit', today_counts: @today_counts, yesterday_counts: @yesterday_counts, week_counts: @week_counts, last_week_counts: @last_week_counts
            
        .chart
          h3
            | Daily Transition
            
          canvas#bookLineChart
          
        .search_book_count
          h3
            | Investigation
          .w-50
            = render 'users/investigation', user: @user
     