config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get 'followings' => 'relationships#following'
    get 'followed' => 'relationships#followed'
    resource :relationships, only: [:create, :destroy]
    get 'rooms' => 'rooms#chat_rooms'
  end
  post 'users/:id/book_count' => 'users#book_count', as: 'book_count'
  
  post 'search' => 'search#search', as: 'search'
  
  post 'dm/:id' => 'rooms#create_dm', as: 'start_dm'
  
  resources :rooms, only: [:index, :create, :show, :new, :edit, :update] do
    get 'detail' => 'rooms#detail', as: 'detail'
    get 'new_email' => 'rooms#new_email', as: 'new_email'
    post 'send_email' => 'rooms#send_email', as: 'send_email'
    resource :room_users, only: [:create, :destroy]
  end
  resources :chats, only: [:create, :index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  
  has_many :chats, dependent: :destroy
  
  attachment :image
  
  validates :name, presence: true
  
  def opponent_for(user)
    room_users.where.not(user_id: user.id).first.user
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_dm_room, only: [:create_dm]
  before_action :check_mutual_follow, only: [:create_dm]
  before_action :set_book, only: [:index, :chat_rooms, :detail]
  before_action :set_room, only: [:new, :show, :edit, :update, :detail, :send_email, :new_email]
  before_action :check_collect_user, only: [:chat_rooms]
  

  def index
    @rooms = Room.where(is_direct_message: false)
  end
  
  def chat_rooms
    @rooms = current_user.rooms
  end

  def new; end
  
  
  def create
    @room = current_user.admin_rooms.build(room_params)
    @room.room_users.build(user_id: current_user.id)
    if @room.save
      redirect_to room_path(@room)
    else
      render 'new'
    end
    
  end
  
  def create_dm
    room = current_user.admin_rooms.build(is_direct_message: true, name: @user.name)
    room.room_users.build([{user_id: current_user.id}, {user_id: @user.id}])
    room.save
    redirect_to room_path(room)
  end
  
  def show
    @chat = Chat.new
    if @room.is_direct_message?
      @opponent_user = @room.opponent_for(current_user)
    end
  end
  
  def edit; end
    
  def update
    @room.update(room_params)
    redirect_to room_detail_path(@room)
  end
  
  def detail
    @room = Room.find(params[:room_id])
    if @room.is_direct_message
      redirect_back(fallback_location: rooms_path)
    end
  end
  
  def send_email
    @room = Room.find(params[:room_id])
    @users = @room.users
    @title = params[:title]
    @content = params[:content]
    if @title.present? && @content.present? && RoomMailer.group_email(@users, @title, @content).deliver
      render 'rooms/finish_email'
    else
      render :new_email
    end
  end
  
  def new_email
  end
  
  private
  def room_params
    params.require(:room).permit(:name, :image, :introduction)
  end
  
  def check_dm_room
    @user = User.find(params[:id])
    room = current_user.dm_room_for(@user)
    if room.present?
      redirect_to room_path(room)
    end
  end
  
  def check_mutual_follow
    unless current_user.mutual_follow?(@user)
      redirect_back(fallback_location: books_path)
    end
  end
  
  def set_room
    if params[:room_id].present?
      @room = Room.find(params[:room_id])
    else
      @room = Room.find_or_initialize_by(id: params[:id])
    end
  end
  
  def check_admin
    unless @room.admin_id == current_user.id
      redirect_back(fallback_location: rooms_path)
    end
  end
  
  def check_collect_user
    user = User.find(params[:user_id])
    unless user == current_user
      redirect_back(fallback_location: rooms_path)
    end
  end
  
  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_chat_rooms.html.slim
table.table.table-hover.table-inverse
  tbody
    - rooms.each do |room|
      tr
        td
          - if room.is_direct_message
            = link_to room_path(room) do
              = attachment_image_tag(room.opponent_for(current_user), :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg")
          - else
            = link_to room_path(room) do
              = attachment_image_tag(room, :image, :fill, 50, 50, fallback: "no-image-icon.jpg")
            
        td
          - if room.is_direct_message
            = link_to room_path(room) do
              = room.opponent_for(current_user).name
          - else
            = link_to room_path(room) do
              = room.name
        td 
          - unless room.is_direct_message
            i.fas.fa-user-friends
            = room.room_users.count

        td.text-secondary
          - if room.chats.present?
            = room.chats.last.content
        
        td.text-secondary
          - if room.chats.present?
            = room.chats.last.created_at.strftime('%m/%d %H:%M')
          
        td
          - if room.is_direct_message == true
            span.badge.badge-primary
              | DM
          - elsif room.admin_id == current_user.id
            span.badge.badge-danger
              | Admin

app/views/rooms/_detail.html.slim
.card.card-body.w-50
  h3.card-title
    = attachment_image_tag(room, :image, :fill, 50, 50, fallback: "no-image-icon.jpg")
    = room.name + "　"
    - if room.admin_id == current_user.id
      = link_to "", edit_room_path(room), class: "fas fa-edit text-secondary text-decoration-none fa-xs"
      = "　　"
      = link_to "", room_new_email_path(room), class: "fas fa-envelope text-secondary text-decoration-none fa-xs"

  h4.card-subtitle.mb-2.text-muted
    | introduction
      
  p.card-text.mb-5
    = room.introduction
    
  h4.card-subtitle.mb-2.text-muted
    | members　

    i.fas.fa-user-friends.fa-xs
      = room.room_users.count
  
  - room.users.each do |user|
    p
      = user.name
    
  = render "join_room_btn", room: room, user: current_user
  
  - if current_user.joined?(room)
    = link_to "Go to Chat !", room_path(room), class: "btn btn-outline-success mt-3"
    
  
  

app/views/rooms/_dm_btn.html.slim
- if current_user.mutual_follow?(user)
  = link_to 'DM', start_dm_path(user), method: :post, class: 'btn btn-outline-primary btn-block' 

app/views/rooms/_form.html.slim
= form_with model: room, local: true do |f|
  = render 'layouts/errors', obj: room
  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :introduction
    = f.text_area :introduction, class: 'form-control', style: 'height: 200px;'
  
  .field
    = f.label :image
    = f.attachment_field :image, class: 'form-control-file'
  .actions
    = f.submit class: 'btn btn-success'

app/views/rooms/_index.html.slim
table.table.table-hover.table-inverse
  tbody
    - rooms.each do |room|
      tr
        td
          = attachment_image_tag(room, :image, :fill, 50, 50, fallback: "no-image-icon.jpg")
            
        td
          = link_to room.name, room_detail_path(room)

        td 
          i.fas.fa-user-friends
          = room.room_users.count
        td.join_room_btn
          = render 'join_room_btn', user: current_user, room: room
          
        td
          - if room.admin_id == current_user.id
            = link_to "edit", edit_room_path(room), class: "btn btn-success"

app/views/rooms/_join_room_btn.html.slim
- if user.joined?(room)
  = link_to "joining", room_room_users_path(room), method: :delete,  class: 'btn btn-info btn-block'
- else
  = link_to "join", room_room_users_path(room), method: :post, class: 'btn btn-secondary btn-block'

app/views/rooms/chat_rooms.html.slim
= render 'search/form'
.container.px-5.px-sm-0
  = render 'layouts/errors', obj: @book
  .row
    .col-md-3
      h2
        | User info
      = render 'users/info', user: current_user
      h2.mt-3
        | New book
      = render 'books/form', book: @book
    .col-md-8.offset-md-1
      h2.d-inline-block
        | Chat Rooms
      
      = link_to "", new_room_path, class: 'fas fa-plus-circle fa-2x text-success text-decoration-none text-right'
      = render 'rooms/chat_rooms', rooms: @rooms

app/views/rooms/detail.html.slim
= render 'search/form'
.container.px-5.px-sm-0
  = render 'layouts/errors', obj: @book
  .row
    .col-md-3
      h2
        | User info
      = render 'users/info', user: current_user
      h2.mt-3
        | New book
      = render 'books/form', book: @book
    .col-md-8.offset-md-1
      h2.d-inline-block
        | Room Detail
      
      = render 'rooms/detail', room: @room

app/views/rooms/edit.html.slim
.container
  .row
    .col-8.offset-2
      
      h2
        | Edit Room
      
      = render 'rooms/form', room: @room
      

app/views/rooms/finish_email.html.slim
.container
  .row
    .col-sm-12.col-md-12.col-lg-8.px-5.px-sm-0.mx-auto
      h1
        | Delivery of letters
      h3
        | The following information has been sent
        
      table.table.table-bordered
        tr
          th.w-25
            | To
          td
            = @room.name
        tr
          th
            | Title
          td
            = @title
        tr
          th
            | Content
          td
            = @content
    
      = link_to 'room detail',room_detail_path(@room), class: 'btn btn-outline-info'

app/views/rooms/index.html.slim
= render 'search/form'
.container.px-5.px-sm-0
  = render 'layouts/errors', obj: @book
  .row
    .col-md-3
      h2
        | User info
      = render 'users/info', user: current_user
      h2.mt-3
        | New book
      = render 'books/form', book: @book
    .col-md-8.offset-md-1
      h2
        | Chats
      = render 'rooms/index', rooms: @rooms

app/views/rooms/new.html.slim
.container
  .row
    .col-8.offset-2
      
      h2
        | Create Room
      
      = render 'rooms/form', room: @room

app/views/rooms/new_email.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h1
        | Event Mail
      
      = form_with url: room_send_email_path(@room), local:true do |f|
        .form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :content
          = f.text_area :content, class: 'form-control'
        .form-group
          = f.submit 'Send', class: 'btn btn-success'

app/views/rooms/show.html.slim
.container
  .row
    .col-8.offset-2
      h2.title.d-inline-block
        - if @room.is_direct_message
          = attachment_image_tag(@opponent_user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg")
          = "to " + @opponent_user.name
        - else
          = link_to room_detail_path(@room), class: "text-decoration-none" do
            = attachment_image_tag(@room, :image, :fill, 50, 50, fallback: "no-image-icon.jpg")
            = " " + @room.name + " "
            i.fas.fa-user-friends.fa-xs.text-secondary
              = @room.room_users.count.to_s
    
        
      .chats.border style = "overflow-y:scroll; #f0ffff"
        = render 'chats/index', chats: @room.chats
      .chat_form
        = render 'chats/form', chat: @chat, room: @room
      
      
      