config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get 'followings' => 'relationships#following'
    get 'followed' => 'relationships#followed'
    resource :relationships, only: [:create, :destroy]
    get 'rooms' => 'rooms#chat_rooms'
  end
  post 'users/:id/book_count' => 'users#book_count', as: 'book_count'
  
  post 'search' => 'search#search', as: 'search'
  
  post 'dm/:id' => 'rooms#create_dm', as: 'start_dm'
  
  resources :rooms, only: [:index, :create, :show, :new, :edit, :update] do
    get 'detail' => 'rooms#detail', as: 'detail'
    get 'new_email' => 'rooms#new_email', as: 'new_email'
    post 'send_email' => 'rooms#send_email', as: 'send_email'
    resource :room_users, only: [:create, :destroy]
  end
  resources :chats, only: [:create, :index]
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title,presence:true
	validates :body,presence:true,length:{maximum:200}
	
	validates :evaluation, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  acts_as_taggable
  acts_as_taggable_on :categories
	
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
	def self.search_contents(word, range)
		if range == 0
			self.where(["title LIKE?", "#{word}"])
		elsif range == 1
			self.where(['title LIKE?', "#{word}%"])
		elsif range == 2
			self.where(['title LIKE?', "%#{word}"])
		elsif range == 3
			self.where(['title LIKE?', "%#{word}%"])
		end
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :content, presence:true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :content, presence:true, length:{maximum:140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  
  has_many :chats, dependent: :destroy
  
  attachment :image
  
  validates :name, presence: true
  
  def opponent_for(user)
    room_users.where.not(user_id: user.id).first.user
  end
  
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image, destroy: false

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following_users, through: :follower, source: :followed
  
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followed_users, through: :followed, source: :follower
  
  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  
  has_many :admin_rooms, class_name: 'Room', foreign_key: 'admin_id'
  
  has_many :chats
	
  def followed_by?(user)
    followed_users.where(id: user.id).exists?
  end
  
  def mutual_follow?(user)
    self.followed_by?(user) && user.followed_by?(self)
  end
  
  def self.search_contents(word, range)
  	if range == 0
  		self.where(['name LIKE?', "#{word}"])
  	elsif range == 1
  		self.where(['name LIKE?', "#{word}%"])
  	elsif range == 2
  		self.where(['name LIKE?', "%#{word}"])
  	elsif range == 3
  		self.where(['name LIKE?', "%#{word}%"])
  	end
  end
  
  def dm_room_for(user)
    my_dm_rooms_id = self.rooms.where(is_direct_message: true).pluck(:id)
    return user.rooms.find_by(id: [my_dm_rooms_id])
  end
  
  def count_books_for(date)
    self.books.where(created_at: date.all_day).count
  end
  
  def joined?(room)
    room_users.where(room_id: room.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:index, :show, :edit, :update, :destroy]
  before_action :view_count, only: [:show]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :set_books, only: [:index]
  

  def show
    @book_comment = BookComment.new
  end

  def index; end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :evaluation, :category_list)
  end

  def ensure_correct_user
    unless @book.user == current_user
      redirect_to books_path
    end
  end
  
  
  
  def view_count
    @book.update(page_views: @book.page_views + 1)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_book, only: [:index]

  def create
    chat = current_user.chats.new(chat_params)
    chat.save
    redirect_back(fallback_location: books_path)
  end
  
  def index
    @room = current_user.rooms
  end
  
  
  private
  def chat_params
    params.require(:chat).permit(:content, :room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/room_users_helper.rb
module RoomUsersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.slim
- if obj.errors.any?
  #error_explanation
    h3
      = pluralize(obj.errors.count, "error")
      |  prohibited this obj from being saved:
    ul
      - obj.errors.full_messages.each do |message|
        li
          = message

app/views/layouts/_footer.html.slim
footer
  .container.mt-5
    .row
      .mx-auto
        p
          | CopyRight Infratop.inc

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    .container
      a.navbar-brand[href="/"]
        span
          | Bookers
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarNavDropdown.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          - if user_signed_in?
            li
              = link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light'
            li
              = link_to ' Chats', user_rooms_path(current_user), class: 'fas fa-envelope nav-link text-light'
            li
              = link_to ' Users',users_path,class: 'fas fa-users nav-link text-light'
            li
              = link_to ' Books',books_path ,class: 'fas fa-book-open nav-link text-light'
            li
              = link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light'
          - else
            li
              = link_to ' Home',root_path,class: 'fas fa-home nav-link text-light'
            li
              = link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light'
            li
              = link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light'
            li
              = link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Bookers2Ver2
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"]
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"
  body
    = render 'layouts/header'
    main
      p#notice
        = notice
      
      = yield
    = render 'layouts/footer'